### ISSUE TITLE
use python3.11 Self 

### ISSUE THREAD

**Issue by tandav** [tandav/musiclib#107]
https://peps.python.org/pep-0673/

**Comment by Sandhya-08** [comment]
Hi,
Can you please assign this task to me? Or can able the option to upload the files.

**Comment by tandav** [comment]
Hi, this task is not can be done until python3.11 is released (October 24, 2022). After release [this line](https://github.com/tandav/musictool/blob/d7f6cc2b41a1cc6c6900e05002703f134aa93db2/musictool/noteset.py#L41) should be removed and `from typing import Self` should be added on top of the file. Also `3.10` should be updated to `3.11` in `setup.cfg`, `Makefile` and `.github/workflows/ci.yml`.

**Comment by tandav** [comment]
While python3.11 release is on October 24, 2022, this repo uses [setup-python github action](https://github.com/tandav/musictool/blob/master/.github/workflows/ci.yml#L18). You can use 3.11 in that action to prepare the PR and all tests will pass, I can merge it on October 24
