### ISSUE TITLE
пусть все думают что занят чем-то важным

### ISSUE THREAD

**Issue by andrei-valikov** [tandav/musiclib#128]

**Comment by andrei-valikov** [comment]
ещё в описание к профилю накидаю 100500 самоидентификаций
я то я это

**Comment by tandav** [comment]
Есть такое, го созвон?

**Comment by tandav** [comment]
мистер абстрактный чел который ничего не делает а целый год изучает виртуальные загоны и думает что такой положняк должен быть у всех

**Comment by andrei-valikov** [comment]
чем больше ты делаешь, тем ты лучше
