### ISSUE TITLE
а по сути

### ISSUE THREAD

**Issue by andrei-valikov** [tandav/musiclib#133]
да навязывание
а то что?
тандав
в нике хотелось бы танцевать
но в реальности занимаюсь набиванием квадратиков на гитхабе
может кому-то будет интересно что я делаю
а может нет
однажды меня заметят и я стану популярным
нужно просто ещё немного поработать
там доделать

**Comment by tandav** [comment]
Критикуя предлагай (с) Оксимирон
пока у тебя были только доебки, а что ты сам делаешь так и не сказал
тоесть для тебя все плохо/все не то/ но сам ты ничего не делаешь 
подробнее раскрыл мысль тут https://github.com/tandav/pipe21/issues/23#issuecomment-1474762165 

ты делаешь сделал акцент на том что типа все ради квадратиков/заметности - но нет, суть в самих проектах
